server:
  port: 8081
  address: 0.0.0.0
spring:
  application:
    name: user
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip: 127.0.0.1
        namespace: public
        group: DEFAULT_GROUP
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        namespace: public
        group: DEFAULT_GROUP
  config:
    import: optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/video_user?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
keycloak:
  auth-server-url: http://localhost:8080/auth  # Keycloak 地址
  realm: VideoApp                              # 领域名称
  resource: videoback                       # UserService 的客户端 ID（若 Keycloak 中注册了，需一致；也可省略，通过公钥验证）
  bearer-only: true                            # 资源服务，仅验证 JWT，不处理重定向
  use-resource-role-mappings: true             # 启用角色映射
logging:
  level:
    org.springframework.security: DEBUG
    org.keycloak: DEBUG